name: JPEG to MJPEG
version: 0.1.0
slug: jpeg-to-mjpeg
description: 'A "Converter" for weird IP cameras. It requests the current JPEG from the given URL and puts it into a MJPEG Stream.'
url: https://github.com/stuchlyf/hassio-addon-jpeg-to-mjpeg
codenotary: stuchlyf@stuchlyf.dev
startup: services
homeassistant: 0.113.2
arch:
- aarch64
- amd64
- armv7
init: false
ports:
  80/tcp: 42069
ports_description:
  80/tcp: The port on which the MJPEG stream is reachable via HTTP.
discovery:
- jpeg-to-mjpeg
host_network: true
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  camera_url: str
  delay: float
image: docker pull ghcr.io/stuchlyf/hassio-addon-jpeg-to-mjpeg:main
